import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-5`}
      >
        <div className="flex gap-3">
          Root
          <Link href="/hello">Hello</Link>
          <Link href="/hi">Hi</Link>
          <Link href="/hi/time">Hi Night</Link>
          <Link href="/parallel">Parallel</Link>
          <Link href="/intercept">Intercept</Link>
          <Link href="/photos">Photo</Link>
        </div>
        <div>{children}</div>
        <hr />
        <footer>Footer</footer>
      </body>
    </html>
  );
}
