@baseUrl = http://localhost:8080

### user - all
GET{{baseUrl}}/users

### user - get 1
GET{{baseUrl}}/users/1

### user add
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Kunbam",
  "email": "abc@gmail.com",
  "mobile": "010-1234-1234"
}

> {%
    client.global.set("newerId", response.body.id);
%}

### user - update
PATCH {{baseUrl}}/users/{{newerId}}
Content-Type: application/json

{
    "name": "Sico",
    "email": "abc22@gmail.com",
    "mobile": "010-1234-5678"
}

### user - delete
DELETE {{baseUrl}}/users/{{newerId}}

### user - get one
GET {{baseUrl}}/users/{{newerId}}

### user - get 1
GET {{baseUrl}}/users/1

### hello
GET {{baseUrl}}/hello

### hi
GET {{baseUrl}}/hi?name=Kun

> {%
    client.global.set("greeting", response.body);
 %}


### hi/{name}
GET{{baseUrl}}/hi/{{greeting}}
